/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.go.GolangRuntimeModule;
import org.xtext.example.go.GolangStandaloneSetup;
import org.xtext.example.go.ide.GolangIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GolangIdeSetup extends GolangStandaloneSetup {
  @Override
  public Injector createInjector() {
    GolangRuntimeModule _golangRuntimeModule = new GolangRuntimeModule();
    GolangIdeModule _golangIdeModule = new GolangIdeModule();
    return Guice.createInjector(Modules2.mixin(_golangRuntimeModule, _golangIdeModule));
  }
}
