/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.ide;

import org.xtext.example.go.ide.AbstractGolangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GolangIdeModule extends AbstractGolangIdeModule {
}
