/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.go.parser.antlr.internal.InternalGolangParser;
import org.xtext.example.go.services.GolangGrammarAccess;

public class GolangParser extends AbstractAntlrParser {

	@Inject
	private GolangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGolangParser createParser(XtextTokenStream stream) {
		return new InternalGolangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "VarDecl";
	}

	public GolangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GolangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
