/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go;

import org.xtext.example.go.GolangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GolangStandaloneSetup extends GolangStandaloneSetupGenerated {
  public static void doSetup() {
    new GolangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
