/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go;

import org.xtext.example.go.AbstractGolangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GolangRuntimeModule extends AbstractGolangRuntimeModule {
}
