/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.validation;

import org.xtext.example.go.validation.AbstractGolangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GolangValidator extends AbstractGolangValidator {
}
