/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.go.ui.internal.GoActivator;

public class GolangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GoActivator.getInstance().getInjector("org.xtext.example.go.Golang");
	}

}
