/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GolangStandaloneSetup extends GolangStandaloneSetupGenerated {

	def static void doSetup() {
		new GolangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
