/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.go.ui.AbstractGolangUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GolangUiModule extends AbstractGolangUiModule {
  public GolangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
