/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.go.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.go.ui.internal.GoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GolangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GoActivator.getInstance().getInjector(GoActivator.ORG_XTEXT_EXAMPLE_GO_GOLANG);
	}
	
}
